apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uppy-server
  namespace: uppy
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard